### PR TITLE
Clean multiselect style

### LINKED ISSUE #24: Season selection button arrow misaligned
Goto a page with a season selection button on it, such as the /winrates page as a signed in subscriber.

On latest chrome on a windows 10 PC, you can see the arrow in the season selection button is misaligned vertically.

image

I'm also curious as to other peoples thoughts regarding why the text is in a blue box by itself and if we should also change that?

### PR DESCRIPTION
**Pull request by zsol**
Fixes #24 
Before: 
image

After:
image
image

### CODE REVIEW

**Comment by zsol** [comment]
To be fair, this dropdown component is extremely opinionated about its own styling, so these commits do some terrible `!important` hacks to get around them. It might be worth looking into a better component in the future

**Comment by synap5e** [comment]
Can you rebase this onto master? 
I squashed the merge (should have rebased, sorry about that) so the hash for the script commit is changed.

**Comment by zsol** [comment]
Rebased.

**Comment by synap5e** [comment]
@benolot yeah the integrity is probably a copypaste from when it was a remote file.
Local shouldn't need integrity or crossorigin stuff.

**Pull request merged**
