### PR TITLE
Style tweaks and fixes for games list rows

### PR DESCRIPTION
**Pull request by JWSenteney**
Fixed alignment issue with some numbers compared to the rest of the text and removed the gradient from the map images and attempted to give them a cleaner look.

### CODE REVIEW

**Comment by JWSenteney** [comment]
Also added images for Paris.

**Comment by teamcoltra** [comment]
Have you checked this PR against mine?

**Comment by JWSenteney** [comment]
Yeah, I looked over yours and I don't believe we touched the same stuff.  Let me know if you notice anything that looks like it could cause a conflict.

**Comment by teamcoltra** [comment]
Thanks @JWSenteney lets get you added as a contributor for design cc: @all-contributors

**Comment by teamcoltra** [comment]
@all-contributors please add @JWSenteney for design

**Pull request merged**
